Make the expand/collapse click area include the background
WFCD/warframe-hub pull request #137
Opened 2018-06-29 15:09 UTC by dsinn

### Make the expand/collapse click area include the background
---
**Summary (short):**
Closes #133.

---
**Description:**
Basically what I suggested in the comments for the issue, except I needed to do some front-end tweaks afterwards.

---
**Fixes issue (include link):**
#133

---
**Mockups, screenshots, evidence:**

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

2018-06-29 15:10 UTC, dsinn commented
I did the same thing for the Acolytes code-wise, but I'm not sure how to easily test them when they're not up.

2018-06-29 15:14 UTC, TobiTenno commented
did you do it for baro? I haven't looked yet

2018-06-29 15:19 UTC, TobiTenno requested changes

2018-06-29 15:19 UTC, TobiTenno commented on assets/js/updaters.js
> +                '<a href="#voidTraderInventoryPanel" data-toggle="collapse" class="panel-heading show">\n' +
could you add a text-center to the anchor classes here, that way it's consistent with the other panels?

2018-06-29 15:19 UTC, TobiTenno commented on assets/js/updaters.js
>                  '<table class="table table-striped table-hover ">\n' +
looks like the headings on the table are a tad misalinged on mobile resolutions... If you see a fix for it, could you add that?

2018-06-29 15:21 UTC, dsinn commented
Yeah, I wrote this a while ago but specifically waited for Baro to appear because I'm not aware of a convenient way to inject data for testing.

2018-06-30 20:18 UTC, TobiTenno approved these changes

2018-06-30 20:18 UTC, merged