Heart of Deimos
WFCD/warframe-hub pull request #451
Opened 2020-09-03 07:12 UTC by Aericio

**Summary:**
Add bounties for Heart of Deimos, along with the bounty refresh cycle.

---
**Fixes issue (include link):**
https://github.com/WFCD/warframe-hub/issues/449

---
**Mockups, screenshots, evidence:**
![image](https://user-images.githubusercontent.com/16523741/92082705-9aeba800-ed60-11ea-907b-33f8e0679026.png)
![image](https://user-images.githubusercontent.com/16523741/92082880-db4b2600-ed60-11ea-8fe7-8d5dba0bef5f.png)

2020-09-03 07:15 UTC, EricSihaoLin commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WFCD/warframe-hub/pullRequest?prid=6116597&bid=20017546)

2020-09-03 07:15 UTC, EricSihaoLin commented on src/components/panels/TimePanel.vue
> +              <span style="text-transform: capitalize;">{{
Codacy found an issue: [Delete `;`](https://app.codacy.com/manual/WFCD/warframe-hub/pullRequest?prid=6116597)

2020-09-03 07:23 UTC, EricSihaoLin commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WFCD/warframe-hub/pullRequest?prid=6116597&bid=20017546)

2020-09-04 02:22 UTC, TobiTenno commented
time.vome looks wrong

2020-09-04 02:32 UTC, TobiTenno requested changes
apart from the cases you have in place, and the initialWorldstate changes, looks good. if you can solve my qualms, i'm all for this.


also, make sure you add `time` entries for `fass` and `vome`, as they don't currently exist, which is why we're seeing `Time.Fass`, right now.

![image](https://user-images.githubusercontent.com/7128721/92193044-fc794880-ee2c-11ea-9761-ac2dd7ba774f.png)

2020-09-04 02:32 UTC, TobiTenno commented on src/assets/json/components.json
> +      "type": "Entrati"
ty for repurposing this 👍

2020-09-04 02:32 UTC, TobiTenno commented on src/assets/json/initialWorldstate.json
> -    },
why moved?

2020-09-04 02:32 UTC, TobiTenno commented on src/assets/json/initialWorldstate.json
> -    },
why moved?

2020-09-04 02:32 UTC, TobiTenno commented on src/assets/json/initialWorldstate.json
> +      "razorbackProgress": "2000-01-01T01:00:00.000Z",
should be a float in a string, not a timestamp

2020-09-04 02:32 UTC, TobiTenno commented on src/components/panels/TimePanel.vue
> +                vome: time.state == 'vome',
should use `===`

(unsure why eslint didn't complain)

if possible, please fix the others, too


also...

```suggestion
                fass: time.active === 'fass',
                vome: time.active === 'vome',
```

2020-09-04 06:14 UTC, Aericio commented
@TobiTenno I don't know why those were changed/moved. I didn't manually edit the worldstate file, I ran `initialWorldstateUpdater.js` for those. Should I rollback and manually edit it, instead?

2020-09-04 11:45 UTC, TobiTenno commented
Probably just manually edit the values for stuff that has the wrong data type. Sorry for the confusion, you're doing what you should be.

For the time bits, there should be a time object in the langs/en.json

2020-09-05 01:27 UTC, EricSihaoLin commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/WFCD/warframe-hub/pullRequest?prid=6116597&bid=20017546)

2020-09-05 02:43 UTC, TobiTenno commented on src/lang/de.json
> +    "fass": "fass",
could you use the title case versions of these so the transformation is more of a backup?

2020-09-05 03:03 UTC, TobiTenno approved these changes

2020-09-05 03:03 UTC, merged