New Theme + optimize images
WFCD/warframe-hub pull request #83
Opened 2018-01-13 10:13 UTC by NeXoGone

### Warframe Hub Pull Request
---
---

**Summary (short):**

- New dark theme **(Eidolon)**
- Moving theme icons and backgrounds to **img/themes**
- Reducing images file sizes: **32MB -> 24,5MB**

---

(Check one)
- [ ] Issue fix
- [x] Suggestion fulfillment

2018-01-13 13:11 UTC, TobiTenno commented
eidolon theme doesn't work

2018-01-13 16:15 UTC, TobiTenno commented
I'd add logic to force a grid update, since this forces everything down a bit and on the set of components i'm using, some things are floating down behind the footer (which doesn't happen if you force a repack)

2018-01-15 03:53 UTC, TobiTenno commented
still need to force update grid after clicking the theme switcher for this

2018-01-16 05:22 UTC, TobiTenno commented
@NeXoGone do you need help with it?

2018-01-16 10:32 UTC, NeXoGone commented
@TobiTenno yes... I do not understand what I need to add ._.

2018-01-16 13:37 UTC, TobiTenno commented
It's all good. you should just need to add a function call `updateGrid();` after [this if/else block](https://github.com/NeXoGone/warframe-hub/blob/cb05bfa1ca7c66d66477c3e1033f9e939e5923e9/views/partials/eidolon-theme.hbs#L17)

2018-01-16 17:20 UTC, TobiTenno commented
looks good

2018-01-16 19:23 UTC, TobiTenno approved these changes

2018-01-16 19:24 UTC, TobiTenno commented
@EricSihaoLin or @Tithen-Firion if either of you could approve as well, i just like more than one so we know it's been reviewed.

2018-01-16 19:29 UTC, Tithen-Firion requested changes

2018-01-16 19:29 UTC, Tithen-Firion commented on views/partials/eidolon-theme.hbs
> +	$(function() {
replace tabs with spaces

2018-01-16 19:35 UTC, EricSihaoLin approved these changes
I have briefly looked through the changes, I have no problems with it. 

Conditional approve: Tabs are standardized to 2 spaces to save space on screen.

2018-01-16 19:47 UTC, TobiTenno commented on views/partials/eidolon-theme.hbs
> +	$('#eidolon').click(function() {
if it's spaces now, it needs to be 2 instead of.... 8

2018-01-16 19:47 UTC, TobiTenno commented on views/partials/eidolon-theme.hbs
> +	$('#eidolon').click(function() {
and it looks like it's still tabs

2018-01-16 19:48 UTC, Tithen-Firion requested changes

2018-01-16 19:48 UTC, Tithen-Firion commented on assets/css/main.eidolon.css
> +	/* For list items that go over labels */
tab

2018-01-16 19:48 UTC, Tithen-Firion commented on views/partials/eidolon-theme.hbs
> +	$('#eidolon').click(function() {
more tabs in this file

2018-01-16 20:53 UTC, Tithen-Firion approved these changes

2018-01-16 21:07 UTC, merged